### ISSUE TITLE
Request Operational example 

### ISSUE THREAD

**Issue by JohanIskandar** [hyperledger-labs/microfab#127]
Hello,
   Could you guys please provide the operational example. I am following https://fabcar-samples.github.io/docs/networks/microfab/
but when `peer lifecycle chaincode install fabcarcc.tgz`

Error: failed to retrieve endorser client for install: endorser client failed to connect to sampleorgpeer-api.127-0-0-1.nip.io:8080: failed to create new connection: context deadline exceeded

    Please help so I can continue learning about this great tool. Thank you.

regards,

Johan

**Comment by mbwhite** [comment]
@JohanIskandar sorry for the massive delay in responding... pr #134  should provider what you need!
