### ISSUE TITLE
These files are labeled as IBM Confidential, and are not open source. If they are mis-labeled you should update the file headers, otherwise they should not be used and must be removed from your repository.

### ISSUE THREAD

**Issue by ryjones** [hyperledger-labs/microfab#154]
[These files are labeled as IBM Confidential, and are not open source. If they are mis-labeled you should update the file headers, otherwise they should not be used and must be removed from your repository.](https://github.com/hyperledger-labs/microfab/blob/d75784406b3b09b803de536101d366c28cdfcfbc/internal/pkg/config/config.go#L1-L11)

**Comment by mbwhite** [comment]
That's a mistake.. will correct the file
